name: Node.js App CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures the 'deploy' job runs only if 'test' succeeds
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }}
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
